### ISSUE TITLE
AutoTotem weird behavior

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#122]
Using Force + Inventory with no totems will break stuff, as quoted
> left click doesnt allow me to move items, and right click will place half my items into a new slot automatically

**Comment by S-B99** [comment]
Cannot reproduce

**Comment by Fu-ms** [comment]
When using Force + Inventory with NO totems in your inventory (even off hand), taking a totem from a hopper or chest will crash your game.

**Comment by S-B99** [comment]
Oop, forgot to test with no totems. Will try later

**Comment by Fu-ms** [comment]
I believe it is to do with attempting to access the offhand slot when it physically cannot access it? Maybe try and rework the disable in GUI section.

**Comment by S-B99** [comment]
Just have it disable with no totems, or have an option to do so

**Comment by Fu-ms** [comment]
Yes correct. Ill give it a test now.

**Comment by S-B99** [comment]
Upload a video if you can. If not I'll test when I get home (~2h)

**Comment by S-B99** [comment]
![Video link](https://youtu.be/cQYh3Lwy-eU)

Tested myself, I cannot reproduce this. Also tried when not inside an inventory. Please provide a video of this issue if you can still reproduce it

**Comment by S-B99** [comment]
Reopened, I realised it does fuck up inventory with no totems, you can't move items normally

**Comment by S-B99** [comment]
Not wontfix, this was actually fixed
