### ISSUE TITLE
AutoEZ

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#129]

**Comment by Deauthorized** [comment]
https://www.minecraftforge.net/forum/topic/77849-1122-on-player-kill-method/?tab=comments#comment-372990

**Comment by cookiedragon234** [comment]
Doesn’t work @deauthorized , that’s a server side event

**Comment by blockparole** [comment]
Oh i think this actually is an available event, should be useable like this:
```
@EventHandler
public Listener<LivingDeathEvent> livingDeathEventListener = new Listener<>(event -> {  });
```
Gonna do some testing.

**Comment by cookiedragon234** [comment]
Wtf I spent ages making some super complicated auto ez and this works?

**Comment by blockparole** [comment]
¯\_(ツ)_/¯ minecraft things

**Comment by Deauthorized** [comment]
> 
> 
> Doesn’t work @Deauthorized , that’s a server side event

just gain access to the server then, ez

**Comment by S-B99** [comment]
Just duplicate the server to client session ez

**Comment by Kami147** [comment]
> Oh i think this actually is an available event, should be useable like this:
> 
> ```
> @EventHandler
> public Listener<LivingDeathEvent> livingDeathEventListener = new Listener<>(event -> {  });
> ```
> 
> Gonna do some testing.
> edit: yeah works

can you elaborate on how you got this to work?

**Comment by S-B99** [comment]
They literally posted the code. What more could you want

**Comment by d1gress** [comment]
`    @EventHandler
    public Listener<LivingDeathEvent> livingDeathEventListener = new Listener<>(event -> { 
        if (event.getEntity() instanceof EntityPlayerMP && event.getEntity() != mc.player) mc.player.sendChatMessage(event.getEntity().getCustomNameTag() + "just got EZ'd!");
    });`

**Comment by Kami147** [comment]
> @EventHandler public Listener<LivingDeathEvent> livingDeathEventListener = new Listener<>(event -> { if (event.getEntity() instanceof EntityPlayerMP && event.getEntity() != mc.player) mc.player.sendChatMessage(event.getEntity().getCustomNameTag() + "just got EZ'd!"); });

ty, love u no homo

**Comment by d1gress** [comment]
also worth noting that i havent tested this because the listener doesnt work for me

**Comment by S-B99** [comment]
Why did you just give a kami skid code sjfjakdk

**Comment by Vonr** [comment]
i dont check profiles
