### ISSUE TITLE
Make gradle commands universal

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#192]
- [ ] make copy os independant
- [ ] make rmOld os independant
- [x] repo for build tools
- [x] build instructions
- [x] modid
- [x] modified package
- [x] rename base packages
- [x] config name

**Comment by S-B99** [comment]
- [ ] modid
- [ ] modified package
- [ ] rename base packages
- [ ] config name

**Comment by Crystallinqq** [comment]
ok

**Comment by d1gress** [comment]
gradle isnt even in the list though

**Comment by S-B99** [comment]
It was in my head
Added it

**Comment by d1gress** [comment]
ok now do it

**Comment by d1gress** [comment]
wait why am i waiting for you i have push access >:)

**Comment by S-B99** [comment]
I have to work todayyy I'll do it later

**Comment by S-B99** [comment]
rest will be left undone as i don't really care about licensing anymore, just use lgpl

**Comment by S-B99** [comment]
See [this](https://github.com/fr1kin/ForgeHax/blob/40d18b8e378d2a226507edb5dccb374ba250965d/build.gradle#L99) for the last one.

**Comment by S-B99** [comment]
For #271 as well
