### ISSUE TITLE
FakePlayer

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/kamiblue#198]
Summoning fake player could work by for example typing kami prefix fakeplayer x y z ( or spawn it in already where u standing ) and enter name from people in your render distance.

Additionally you could make ability to summon fake players by uuid and being able to make them 
either naked or have the same items as you.

As well possible having a txt/ file where it could contain commands like move 10 blocks right 

Rough Example: movement.right.10blocks, jump.samepossition.2times.

Even being able to damage damage as well have a scripted event if they take damage rough example:

damaged.sword.eat.gapple,  move.backwards.3blocks

End result could be something like this.

movement.forward.2blocks,movement.left.2blocks,realplayer,inputwait,damaged.sword.eat.gapple,move.backwards.3blocks

Niche features could be suicide,crystal, suicide.starvation, suicide.totemanimation, suicide,fakeslashkill.

Obviously this will be only visual and you're the only one who can see it.

**Comment by S-B99** [comment]
I'm not sure why you mean by a text file and the last part of the issue, could you elaborate?

**Comment by DontEatOreo** [comment]
The text file is for storing all the events the fakeplayer will perform and for example you could do .fakeplayer play test.txt after you. summoun the fake player

Last part is the fake player having dying animations crystal one is prob the hardest one and probably really hard but essentially it can spawn it fakecrystal and die by it.

Starvation one is slowly taking damage without doing anything.

Totem animation is the fake player getting his totems used up.

SlashKill is pretty much instant death if death message return it could create fakechat message similar to real ones when people do slash kill.

**Comment by S-B99** [comment]
That's just macros with extra steps. And this is essentially useless for what it accomplishes, just login on an alt.

What this could be, is renaming someone else

**Comment by DontEatOreo** [comment]
Even if you don't do the fake player doing stuff part. 
Will be nice to be able to spawn stationary fakeplayer.

**Comment by S-B99** [comment]
This isn't very useful and doesn't accomplish much, especially for the required work.
