### ISSUE TITLE
Spoofed Rotations for modules

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/kamiblue#200]
**Is your feature request related to a problem? Please describe.**
Some servers wont allow AutoTrap to function properly without spoof rotation.

**Describe the solution you'd like**
Add Spoof Rotation as an option.

**Describe alternatives you've considered**

**Additional context**

**Comment by S-B99** [comment]
- [ ] surround
- [ ] autotrap

**Comment by S-B99** [comment]
Now implemented.
