### ISSUE TITLE
Anti-SelfAutoTrap

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/kamiblue#208]
Title.

As it says it will stop using the auto trap if the player entered your hole or it's too close enough for the Auto Trap to trap you in.

It can be toggled in the AutoTrap menu.

Self-trap can be defined as two blocks all around you and a block on top of you blocking your exist.

**Comment by S-B99** [comment]
You can't trap yourself?

**Comment by DontEatOreo** [comment]
> 
> 
> You can't trap yourself?

You can if a player enters same hole as you while u have AutoTrap on you will trap them with you.

**Comment by S-B99** [comment]
That's a bruh moment

**Comment by S-B99** [comment]
Now implemented.
