### ISSUE TITLE
Infinite chat history

### ISSUE THREAD

**Issue by Puffy120** [S-B99/kamiblue#226]
As in history of messages that have been sent

**Comment by d1gress** [comment]
mixins chatgui or something like that

**Comment by Vonr** [comment]
its... done?

**Comment by Vonr** [comment]
well its not infinite but its the highest it can go (2^31-1)

**Comment by S-B99** [comment]
No, it's not done, this is still opened

**Comment by Vonr** [comment]
bruh the infinite chat length branch

**Comment by S-B99** [comment]
It hasn't had any commits to it??

**Comment by Vonr** [comment]
im pretty sure i pred it

**Comment by S-B99** [comment]
https://github.com/S-B99/KAMI/pulls

No you haven't

**Comment by Vonr** [comment]
what da fudgeee github desktop sucks

**Comment by S-B99** [comment]
Bruh just use the website for pulling

**Comment by S-B99** [comment]
pr this aaaaaaaaaa @Vonr

**Comment by zeroeightysix** [comment]
The notchian minecraft server will kick you if you go over the limit. All other servers will probably do so too.

**Comment by d1gress** [comment]
its for commands

**Comment by S-B99** [comment]
This issue was for the chat history not how many characters you can put in

**Comment by zeroeightysix** [comment]
wow the description on this issue did a great job of clearing that up

**Comment by d1gress** [comment]
agreed. my bad for not reading it clearly

**Comment by S-B99** [comment]
I'm sorry my bad

Never heard of someone wanting an infinite command length before either

**Comment by cookiedragon234** [comment]
Already had this stupid conversation on discord where the exact same arguments were bought up. Infinite chat history is maybe a good idea.

**Comment by EmotionalLove** [comment]
notchian mc server will kick you if you send chats over 256 chars, as 086 said. bad feature request. not going to do it.

**Comment by S-B99** [comment]
That's not the feature kasaaaa

https://github.com/S-B99/KAMI/issues/226#issuecomment-562960738

i made this comment here, it's for the actual history of messages sent, i should've updated description

**Comment by EmotionalLove** [comment]
ooh

**Comment by dominikaaaa** [comment]
Reopening as all you need is a forge event 😎

**Comment by cookiedragon234** [comment]
That was a custom event

**Comment by dominikaaaa** [comment]
Nevermind. I forgot to reopen it so I won't do that
