### ISSUE TITLE
Add hclip

### ISSUE THREAD

**Issue by kdb424** [S-B99/kamiblue#246]
**Is your feature request related to a problem? Please describe.**
.hclip and .vclip are useful for dupes on 2b2t historically and Future's DRM is trash

**Describe the solution you'd like**
Add these commands to this client

**Describe alternatives you've considered**
KMS

**Additional context**
See future client's list of features

**Comment by d1gress** [comment]
use .tp lol. i think i can add it but im not sure if i want to cos tp exists

**Comment by kdb424** [comment]
Are they actually the same when it comes to the "under the hood" workings of it? I'll test it on 2b2t and see if that works and report back if I find any success.

**Comment by S-B99** [comment]
Yea, I'd like to know what as well. I think it should be

**Comment by S-B99** [comment]
Closed due to inactivity and tp is the same thing as hclip
