### ISSUE TITLE
Elytrafly speed options

### ISSUE THREAD

**Issue by kristian2830** [S-B99/kamiblue#259]
What i mean is get an elytrafly that takes off .0001 y or something similar every second.

**Comment by kdb424** [comment]
Maybe expand this issue to "Elytrafly options" as others like .flight glidespeed 0.0001 which slows down the fall massively. This is mostly useful on servers such as 2b2t which block upward movement without rockets. Mainly useful for traveling long distances in small tunnels such as highways.

**Comment by S-B99** [comment]
This doesn't have a glidespeed

![Screenshot_20191209_192136](https://user-images.githubusercontent.com/17222512/70484223-29c0e200-1ab9-11ea-9b20-2d76ae6be861.png)

**Comment by S-B99** [comment]
It only changes your motion speed

I can add options but the default is mostly best and I can guarantee you new players will fuck with tem

**Comment by kdb424** [comment]
On any server that doesn't have a working anticheat allowing you to fly up with this, I agree. Maybe add a command and no gui access to prevent it from being messed with unless needed?

**Comment by S-B99** [comment]
No it literally doesn't have a setting for that

**Comment by Itistheend** [comment]
The way ElytraFlight is currently set up, -.003 Y velocity is the closest it can be to 0 while still moving. This is what it is set to. Not sure why lower values don't work.
