### ISSUE TITLE
Have NoFall bucket mode pick up the water bucket after (WIP)

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#29]
Working on this as I have no motivation for anything else

**Comment by S-B99** [comment]
`            if (((System.nanoTime() / 1000000) - systemTime) >= 250)`
This is a thing for time 
^ note for self

**Comment by cookiedragon234** [comment]
if(Duration.between(last, Instant.now()).getSeconds() > 1)

**Comment by blockparole** [comment]
pseudocode:
if player holds bucket and bucket is empty and block below or at player y is water: pick up

**Comment by blockparole** [comment]
```
if (!(mc.player.getHeldItemMainhand().getItem() == Items.BUCKET)) {
    return;
}

Block block = mc.world.getBlockState(mc.player.getPosition()).getBlock();
if (block instanceof BlockLiquid && block.material.equals(Material.WATER)) {
    stuff();
```

**Comment by S-B99** [comment]
God damnit I've been trying to figure out how to check for time properly this entire time and I could've done buckets

**Comment by S-B99** [comment]
So it doesn't pick stuff up when you're just walking around and happen to fall in water I can have placing the bucket toggle a Boolean and then have it toggle again when picked up

**Comment by blockparole** [comment]
yeah that would work, maybe check if player is not on ground, if is not on ground, set a boolean to true after the player fell a distance he would get falldamage at, then its active. after pickup set it to inactive again.

**Comment by S-B99** [comment]
[How do you think I could check if the player is on the ground? I'm having trouble getting this working.](https://hastebin.com/ezazegubuf.java)
