### ISSUE TITLE
Change GUI color to KAMI Blue color (WIP)

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#36]

**Comment by blockparole** [comment]
added pr #37

**Comment by S-B99** [comment]
TO:DO change background tint here to a shade similar to it
![Screenshot_20191025_142148](https://user-images.githubusercontent.com/17222512/67594654-d4ac5500-f732-11e9-9318-98ac7e8838db.png)

**Comment by S-B99** [comment]
And the module on color, and the visible modules button

**Comment by S-B99** [comment]
Changed merged, still have other elements to go

**Comment by S-B99** [comment]
Files related to gui color for reference
This list is incomplete
```
ColourHolder
KamiGUI
GUIColor
KamiFrameUI
RadarUI
TabGuiUI
```

**Comment by S-B99** [comment]
l208 down for reference in KamiGUI

**Comment by S-B99** [comment]
[For reference](https://github.com/S-B99/KAMI/pull/37#discussion_r352232176)
