### ISSUE TITLE
Switch to using mc's library for text color codes

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#417]
Thanks @LeafHacker

[InfoOverlay.java#L92](https://github.com/S-B99/kamiblue/blob/feature/master/src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java#L92)

[ColourUtils.java#L302](https://github.com/S-B99/kamiblue/blob/feature/master/src/main/java/me/zeroeightsix/kami/util/ColourUtils.java#L302)

```
FrankyToday at 8:32 PM
Ideally you would be doing something more like textComponent.appendSibling(new TextComponentString("some string").setStyle(TextFormatting.RED)) 
(psudocode, can't remember the exact mcp names)
```

**Comment by LeafHacker** [comment]
Here's an example from a recent commit of mine

```java
ITextComponent t = new StringTextComponent("");
t.appendSibling(new StringTextComponent(Version.NAME).applyTextStyles(WHITE));
t.appendText(user.getEdition());
t.appendSibling(new StringTextComponent(" " + Version.IMPACT).applyTextStyles(GRAY));

drawString(font, t.getFormattedText(), x, y, user.getEditionTextColor().orElse(0xffffffff)); }
```

**Comment by S-B99** [comment]
😳😳 <3

**Comment by S-B99** [comment]
![2020-01-28-124528_786x474_scrot](https://user-images.githubusercontent.com/17222512/73290282-29e18200-41cc-11ea-813c-5b9110b8ed6a.png)
