### ISSUE TITLE
CrystalAura break attempts setting

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#439]
A setting of how many times to try to break a crystal before giving up, because of ping.

**Comment by 7orivorian** [comment]
This feature alone would make me want to use this client for pvp

**Comment by S-B99** [comment]
Please don't comment "I want this as well", it doesn't contribute anything or help anyone. Instead you could leave a thumbs up on the issue instead of giving loads of people a notification.

**Comment by 7orivorian** [comment]
Sorry, I'm new to github & didn't know people got notified for this lol
