### ISSUE TITLE
Chatprefix toggle

### ISSUE THREAD

**Issue by TobSick** [S-B99/kamiblue#440]
**Is your feature request related to a problem? Please describe.**

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Changing the prefix to; !,@,#,$,...etc. prevents the user from changing slots (using numbers) when crouching.

**Describe the solution you'd like**
>A clear and concise description of what you want to happen.

Having the option to turn off auto command line open on prefix press will resolve this problem.

**Describe alternatives you've considered**
>A clear and concise description of any alternative solutions or features you've considered.

Issue #431 and #436 attempt to solve this problem, but like @Vonr noted this will prevent binds such as !,@,#,$, etc, from working, thus making the feature obsolete.

**Additional context**
>Add any other context or screenshots about the feature request here.

Simply the ability to turn off command line opening on prefix press will fix the problem. This will make the user press t, then prefix for command line.

**Comment by S-B99** [comment]
I don't see why anybody would bind a key to shift + something really.

**Comment by TobSick** [comment]
Don't judge me.

**Comment by Vonr** [comment]
<@563138570953687061> i said it once, ill say it again. make a module for fuck sake

**Comment by S-B99** [comment]
then make a hidden module that doesn't interfere with existing stuff.

**Comment by Vonr** [comment]
just put it in misc
