### ISSUE TITLE
Display Strength in Nametags

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#442]
Also consider making strengthdetect just integrated

**Comment by m-ryals** [comment]
what if it was integrated into nametags somehow? like if the player has strength, the nametag will have the minecraft icon for strength next to it as it would look in the vanilla potion gui?

**Comment by S-B99** [comment]
It already has this in the Text Radar

**Comment by S-B99** [comment]
Although I would prefer nametags honestly

**Comment by S-B99** [comment]
At this point nametags are already cluttered enough, and getting potion effects from the server is very finicky and unreliable.
