### ISSUE TITLE
Surround doesn't work in newer versions

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#459]
Works in v1.1.1 beta latest 
Kicks with
`Internal Exception: io.nettyhandler.codec.EncoderException: java.lang.NullPointerException`
Tested on endcrystal.me

**Comment by Vonr** [comment]
1.1.1?

**Comment by S-B99** [comment]
Idk why but it works in older versions. I broke something

**Comment by Vonr** [comment]
check file history of surround

**Comment by S-B99** [comment]
I think I tested autocenter and there's no other changes. The Netty error is new, I added that mixin for antichunkloadpatch

**Comment by Vonr** [comment]
honestly like just spam all the methods with if (player == null) return

**Comment by S-B99** [comment]
the player isn't null though. this happens when you're already in the server, and going to place a block. if you don't have obby the surround doesn't kick.

**Comment by S-B99** [comment]
With the netty mixin disabled it still happens.
