### ISSUE TITLE
Make AutoFish faster to catch 

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#470]
Make response catch faster

@see gayfish from qther

**Comment by Vonr** [comment]
lmao

**Comment by Vonr** [comment]
no, please do not see gayfish from me

**Comment by Vonr** [comment]
also actually i made response catch slower

**Comment by Vonr** [comment]
you optimally want to listen for fish sound packets and check if your fishing rod bobber is on it

**Comment by Vonr** [comment]
gayfish used lamp and didnt even work

**Comment by S-B99** [comment]
oh xd
