### ISSUE TITLE
Make Aura and OffhandGap compatible

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#478]
Don't aura when gapping

Waiting for #476

**Comment by pol-y-mer** [comment]
future's aura can hit while eating and still finish eating, maybe implement something like that?

**Comment by S-B99** [comment]
I have no idea how that works, and I *think* it only works on 1.7 (eg hypixel) and 1.8 servers

**Comment by S-B99** [comment]
The feature/auraUpgrade branch is working on solving it, but I haven't finished it

**Comment by S-B99** [comment]
Actually this works.

**Comment by S-B99** [comment]
https://cdn.discordapp.com/attachments/677203011021307925/683450526071128199/2020-02-29_16-52-05_Trim.mp4
