### ISSUE TITLE
Whisper uwu option for VisualRange

### ISSUE THREAD

**Issue by pol-y-mer** [S-B99/kamiblue#479]
optimizations and opening an issue solely for organization purposes

**Comment by S-B99** [comment]
Please add labels. Is this a new module? 

Are you working on it? If so, self assign it. 

When is it going to be done? Add a milestone

**Comment by S-B99** [comment]
labelsssss

**Comment by S-B99** [comment]
yes <3

**Comment by S-B99** [comment]
also what does this do alkslkdksa

**Comment by pol-y-mer** [comment]
whispers hi uwu to players when they enter visual range

**Comment by pol-y-mer** [comment]
its an option under visual range im planing to add a few extra greetings as well as a custom one

**Comment by S-B99** [comment]
You can add a string to let people customize it, look at chatprefixcommand and chatprefix
