### ISSUE TITLE
CrystalAura safer option, and improve hitbox detection

### ISSUE THREAD

**Issue by pol-y-mer** [S-B99/kamiblue#480]
the title is a mouthfull, but If crystalaura can take player health into account and also calculate for damage, it can be optimized. also im not sure how long it's been since the place was updated, but it seems like it places slower than other clients. also, add an option to shrink hitboxes of certain entities that do not interact with the player (crystals, arrows, items) and also players, so the client will try to place when enemies are in the middle of two by 1 gaps but the hitbox stops crystal placement.

Heph added a customizable minimum damage as well, and a hit delay

**Comment by S-B99** [comment]
The place literally couldn't be made faster without sacrificing health. Idk what the last part means

**Comment by pol-y-mer** [comment]
hitbox detection is done both client and server side. however, the client will not even try a place if there is a hitbox stopping it which is why you dont see an arm swing and a block flash if you right click on a placable suface that is blocked by an entity with a block. however, the client will try a place if the sethitbox feature is used to set a entities hitbox to something lower than it already is. this is used in reach in the opposite way, to make hitting entities easier

**Comment by S-B99** [comment]
oh xd

i don't understand it h

**Comment by pol-y-mer** [comment]
by lower, i meant 0. lol. theres legit just a function to set the hitbox of an entity clientside then you can place shit inside it unless the server implements a patch to stop that

**Comment by UrM0ther** [comment]
It already takes player damage into account, it just does it very poorly, it wont place in a spot that does less damage than use unless the other spot would kill you.

**Comment by S-B99** [comment]
How is that poorly, it's completely intentional. Maybe add a 'safe' option with the current behavior, and with it disabled it can be more risky and aggressive.

**Comment by UrM0ther** [comment]
Thats what i meant by poorly, its very risky. safe option would be cool

**Comment by S-B99** [comment]
Uh, no? Right now it's extremely safe and that's what people complain about.

**Comment by UrM0ther** [comment]
// If this deals more damage to ourselves than it does to our target, continue. This is only ignored if the crystal is sure to kill our target but not us.
                    // Also continue if our crystal is going to hurt us.. alot

this is from ca code, it ignores anti suicide if it kills the enemy, but by the tine it explodes the crystal, you and the enemy usually has moved serval blocks and the crystal does completely different damage, so its a big risk

**Comment by UrM0ther** [comment]
epic 5 paragraph essay

**Comment by S-B99** [comment]
oh xd

**Comment by pol-y-mer** [comment]
if you could GaAAaAAaZe into the FuTuRe...

**Comment by S-B99** [comment]
@pol-y-mer i added a note at the bottom of the first comment

**Comment by pol-y-mer** [comment]
After researching, here are some updates on this issue.
1 - predicting the future is intensive, and would require a complete rewrite of the ca code in its current state. 
2 - predicting the future requires a data set.
3 - the current place behaviour is actually very good, however, instead of focusing on inefficiently doing more damage, it uses the least crystals to do the most damage possible. ie placing 1 crystal that would pop an enemy in the moment is better than placing multiple crystals that might pop your enemy later.

Although this is daunting, I may try creating a standalone crystal aura mod to predict where players are going based on data I collect over the next few months. I am, however, adding more settings to allow for customized explosion behaviour, and also behaviour that is more "risky" than the current behaviour. Please suggest any customization you would like to see for placement and explosion behaviour.

**Comment by S-B99** [comment]
For placement, see #439 if you wanna do that, and #406 

I personally don't pvp but if anything else comes up I'll leave it here
