### ISSUE TITLE
Toggle CrystalAura targeting tracers

### ISSUE THREAD

**Issue by Flika1999** [S-B99/kamiblue#49]
I personally find the tracers crystal aura draws from the place block to the target to be kind of annoying, it would be nice if you had the option to toggle them on and off.

**Comment by S-B99** [comment]
Crystal aura has tracers lol?
I've seen screenshots but it's never worked on my computer

I'll look into it

**Comment by S-B99** [comment]
Won't be too hard just add a toggle button in menu
