### ISSUE TITLE
AutoPotion

### ISSUE THREAD

**Issue by TobSick** [S-B99/kamiblue#506]
**Behaviour**
When turned on the modules auto drinks potions, but if the potion effect is already active, it does not drink that corresponding potion until the effect is near wearing off, or has worn off.

**Additional**
I dunno about this one. Everything I said above, but auto switch offhand with potion and then drink it, could be an extension of offhandgap. This could free up hotbar space.

**Comment by S-B99** [comment]
I'm adding custom item options to offhand gap, and automatically drinking potions doesn't sound very useful.

**Comment by TobSick** [comment]
I would find it useful. Auto drinking strength potions would be useful in normal pvp.

**Comment by S-B99** [comment]
Not it wouldn't, it would be counterintuitive and make it annoying to pvp.

**Comment by RealIndrit** [comment]
Splash Potion would be kinda nice though?

**Comment by TobSick** [comment]
Just because you wouldn't find it useful

**Comment by S-B99** [comment]
Splash potions is a different issue #
This is for drinking potions.
Just because you might find it useful doesn't mean others would.
As I said, I'm adding custom item options to offhand gap
I already closed this as wontfix

**Comment by TobSick** [comment]
I think others would find it useful. At least add potions to AutoReplenish then?

**Comment by RealIndrit** [comment]
I can Add AutoSplashPotion while Im at it with adding stuff.

**Comment by S-B99** [comment]
Potions don't stack
You can set autoreplenish to 1 and it should work.

**Comment by TobSick** [comment]
Doesn't work at one. Can you add non stacking items to AutoReplenish?

**Comment by S-B99** [comment]
Create an issue for that then.
