### ISSUE TITLE
HoleESP Big Holes

### ISSUE THREAD

**Issue by TobSick** [S-B99/kamiblue#507]
**Describe the solution you'd like**
Option to add appropriate 2x1 holes and 2x2 holes to HoleESP.

**Additional context**
2x1 holes and 2x2 holes are also safe if the player is standing in the middle covering all blocks, therefore I reckon adding an option (as some may not want it) to have 2x1 and 2x2 holes be a part of HoleESP.
Also, I dunno about this, but perhaps a different module could be toggled to centre the player in the holes properly.

**Comment by S-B99** [comment]
Too resource intensive for what it accomplishes.
