### ISSUE TITLE
XRay Opacity

### ISSUE THREAD

**Issue by TobSick** [S-B99/kamiblue#512]
Add an opacity option to Xray.

**Comment by S-B99** [comment]
Why?

**Comment by S-B99** [comment]
The way it currently works makes it near impossible.

**Comment by TobSick** [comment]
Why? Because it is a useful feature.

**Comment by S-B99** [comment]
How is it useful?

**Comment by TobSick** [comment]
Because I use it. Thus it is useful

**Comment by S-B99** [comment]
It offers little to no advantage over completely clear x-ray or wireframe x-ray.

**Comment by TobSick** [comment]
Jeez Bella, are all my suggestions shit?

**Comment by S-B99** [comment]
No, I'm asking why this would be useful, as in how would it be better then the current one? It's currently impossible to do anyways.

**Comment by TobSick** [comment]
All good. But I don't think you've said yes to one of my suggestions tho : (

**Comment by S-B99** [comment]
I'll say yes if it's actually plausible and useful to the majority of people. There's 120 something issues to work on and I do this for free, if it isn't really worth the time I won't do it.

**Comment by TobSick** [comment]
true, i suppose...

**Comment by TobSick** [comment]
So, is this reopened?

**Comment by S-B99** [comment]
![2020-03-15-203118_328x68_scrot](https://user-images.githubusercontent.com/17222512/76714159-ee5b3280-66fb-11ea-995c-10e4ecd70f7c.png)
