### ISSUE TITLE
PvP information for InfoOverlay

### ISSUE THREAD

**Issue by pol-y-mer** [S-B99/kamiblue#520]
totems, crystals, xp, gaps, armor durability, other important info
toggleable
maybe add a surround check?

**Comment by S-B99** [comment]
If you're doing this let me make a branch and do something to infooverlay for you.

**Comment by pol-y-mer** [comment]
ok bet

**Comment by S-B99** [comment]
done

**Comment by pol-y-mer** [comment]
ty <3
