### ISSUE TITLE
getItems() doesn't check offhand

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#532]
This causes it to think it's 0 if all of them are in your offhand and making totem count inaccurate 

@pol-y-mer big brain pls fix xd

**Comment by pol-y-mer** [comment]
will work vv soon

**Comment by S-B99** [comment]
<3 uwu

**Comment by pol-y-mer** [comment]
ok i got this working so im gonna close the issue

**Comment by S-B99** [comment]
closing when merged

**Comment by pol-y-mer** [comment]
oh kk
