### ISSUE TITLE
Toggle Elytra Equipped

### ISSUE THREAD

**Issue by TobSick** [S-B99/kamiblue#540]
**Feature behaviour.**
This would work by having a bind, where when activated the chest slot would be equipped or replaced with an elytra.

**Use**
This would be useful for losers who need to quickly equipped an elytra to run away from a big bad wolf. Or people who don't want to open their inventory to change from chestplate to elytra.

**Additional context**
An option within the module could be toggle, wherein the behaviour would be to toggle between elytra and chestplate, rather than replace.

**Comment by S-B99** [comment]
Duplicate of #409

**Comment by TobSick** [comment]
Thanks
