### ISSUE TITLE
New or less dictator like developer

### ISSUE THREAD

**Issue by r33666** [S-B99/kamiblue#559]
Gather round y'all cos we bout to expose did MF. So like I be on da issues page spitting stray facts when did mf pull up say her bit not even adressin da sitchyeeation then proceeds to censor my ass by closing the thread. Dis manipoolative controlling type behavior could be the downfall of this piece of shit frfr. So EdaR we need to pull out the glizzies, start cwalkin and furthermore, starting a revolootion out here OR *WE* need to exercise our democratic *(#bernie2020)* rights and get this hoe the fuck outta office frfr. For once in place someone be making some sense out here for real. rip John Lennon he a gangsta
*cowboy* *gun*

**Comment by S-B99** [comment]
Speak English or get out.
https://help.github.com/en/github/site-policy/github-event-code-of-conduct
