### ISSUE TITLE
she out here censoring my ass cos she knows im gonna win the election 2/10 developer

### ISSUE THREAD

**Issue by freeboonk112** [S-B99/kamiblue#560]
She knows that if I were to be a candidate for the election for Kami Blue that i would win. Therefore she is censoring me and will not give me a platform to speak freely via banning. I'm out here expressing my opinion of concern regarding the nature of the developer and her similar characteristics to the renown Kim Jong Eun.

regards boonkgang
#freeboonk

**Comment by Vonr** [comment]
get out

**Comment by freeboonk112** [comment]
> get out

PROOF THEYRE TRYING TO CENSOR ME

**Comment by freeboonk112** [comment]
they just be diggin the hole deeper and deeper

**Comment by Vonr** [comment]
@S-B99 honestly private the fucking repo for a day or two

**Comment by freeboonk112** [comment]
@Vonr you think thats gonna do shit. bruh you have no idea what youve got yourself into. From now on everyday new account new posts spreading the word of my peoples oppression

**Comment by Vonr** [comment]
aight lets private the repo forever

**Comment by freeboonk112** [comment]
im gonna make an effort every single day to double the number of issues history until im acknowledged and my account is unbanned

**Comment by freeboonk112** [comment]
@Vonr id hate to have to ruin this for you ;;;((((((((

also id like a public apology

**Comment by freeboonk112** [comment]
and a lobster sandwhich

**Comment by S-B99** [comment]
Dude you need a hobby. I'll take you seriously when you stop trolling.
