### ISSUE TITLE
No Armor Render

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/kamiblue#576]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
There could be a feature in render which doesn't render armor instead it just renders the player skin.

So anyone you see even if they wear armor ,you would only see their skin and not their armor.

**Comment by S-B99** [comment]
This is already a thing.

**Comment by S-B99** [comment]
https://blue.bella.wtf/modules
