### ISSUE TITLE
crystalaura damage is innacurate

### ISSUE THREAD

**Issue by pol-y-mer** [S-B99/kamiblue#578]
for crystalaura damge calculations, as damage gets below around ten, they become extemely innacurate, and waste crystals often. sometimes do no damage at all fixing in pr #521

**Comment by pol-y-mer** [comment]
clowned mysef you literally cant make it better

**Comment by cookiedragon234** [comment]
How can you not make it any better?

**Comment by S-B99** [comment]
^ seconded
