### ISSUE TITLE
Occasional blank screen.

### ISSUE THREAD

**Issue by Lifeisgood72** [S-B99/kamiblue#602]
**Describe the bug**
Sometimes when going through a portal, or when a player is near my tracers, the entire screen goes blank with a light blue-purple colour. Occasionally I can move away and it goes away but most of the time I have to restart my entire game. It has happened so far when:

I go through a portal
I enter freecam
I turn on CameraClip
Someone enters my tracers

**To Reproduce**
Try turning on freecam or going through portals.
**Expected behavior**
My screen not to go blank
**Screenshots**
https://imgur.com/3qrBbJY.jpg

**Additional context**
Using latest version of Kami Blue 1.12.2

**Comment by S-B99** [comment]
Can you post a screenshot of `.enabled` when it happens?

**Comment by S-B99** [comment]
That color is most likely from inventory viewer, and I've never had this bug happen on Linux.

**Comment by S-B99** [comment]
>  Using latest version of Kami Blue 1.12.2

What is the *exact* version that it says in the mod menu by the way?

**Comment by S-B99** [comment]
I had someone tell me that impact's freecam causes this. Use Kami Freecam, not a Kami issue.
