### ISSUE TITLE
AutoFish Auto cast

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#631]
For afk fishing when you get kicked and auto reconnect

**Comment by Vonr** [comment]
so we check if the rod was casted out using boolean variable then if it was and we got disconnected then on reconnect we cast?

**Comment by S-B99** [comment]
I was just gonna have it cast the rod if it wasn't casted honestly.

**Comment by Vonr** [comment]
but the edge cases that you wouldnt want your rod casted

**Comment by S-B99** [comment]
I mean then you can just run the ServerDisconnectEvent listener and have it change a hidden setting.

**Comment by S-B99** [comment]
Would take like 5 minutes but I wanna get schoolwork done first

**Comment by Vonr** [comment]
shrug
