### ISSUE TITLE
XCarry smart option

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#639]
Only cancel if something is in crafting slots.

**Comment by S-B99** [comment]
I haven't found a way to get if items are in crafting slots, `mc.player.inventory` and `mc.player.inventory.mainInventory` don't count it. Tested with and without XCarry on to see if that was the issue, and it wasn't.

**Comment by Tigermouthbear** [comment]
Crafting slots are slots 1-4 in the players inventory

**Comment by S-B99** [comment]
As shown by tests, trying to print that doesn't work, and they are not 1-4.
I've had this image [linked](https://cdn.discordapp.com/attachments/665272588703891476/695629432290803802/300px-Inventory-slots.png) to me, and it appears to be incorrect, as shown by here:
![2020-04-03-094526_1920x1080_scrot](https://user-images.githubusercontent.com/17222512/78368842-431efa00-7592-11ea-96ee-baf19346f045.png)

When the torch is in the first hotbar slot it prints 0. It prints nothing when the torch is in crafting. 

Code:
```java
for (int i = 0 ; i < mc.player.inventory.getSizeInventory() ; i++) {
            if (mc.player.inventory.getStackInSlot(i).getDisplayName().contains("Torch")) {
                Command.sendChatMessage("Slot: " + i);
                Command.sendChatMessage(mc.player.inventory.getStackInSlot(i).getDisplayName());
            }
        }
```

**Comment by Tigermouthbear** [comment]
Then put a torch in all four slots and see what the numbers are

**Comment by S-B99** [comment]
I tried that and it doesn't print anything, unless you mean put 1 torch in each of the crafting slots?

**Comment by Tigermouthbear** [comment]
oh wait nvm I read that wrong

**Comment by S-B99** [comment]
xd yea

idk what to do here so won't fix it is
