### ISSUE TITLE
AntiHole Module

### ISSUE THREAD

**Issue by 2bHacker** [S-B99/kamiblue#640]
A module to help you remove 2020 jds from holes while PvPing. 
It could hit them with a sword and then place a block under them.

**Comment by S-B99** [comment]
This is what holefiller is for

**Comment by cookiedragon234** [comment]
What are "2020 jds"?

**Comment by 2bHacker** [comment]
People who joined 2b in 2020

**Comment by cookiedragon234** [comment]
so... you?

**Comment by Ihackedsctrach** [comment]
kek
