### ISSUE TITLE
Add a freecam mode to make the game think you're still on a block

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/kamiblue#65]
**Describe the bug**
Going freecam makes destroying blocks harder.

**To Reproduce**
1. Go Freecam.
2. Try breaking a block...

**Expected behavior**
Breaking blocks should be same speed.

**Screenshots**

**Additional context**

**Comment by S-B99** [comment]
This isn't really a bug, the game thinks you're actually flying which is why it's slower.

To me when I'm fixing this: solution was posted on discord
