### ISSUE TITLE
Optimize autototem

### ISSUE THREAD

**Issue by ub3rshadow** [S-B99/kamiblue#82]
A slider that allows the user to change the equipping delay of autototem. Would allow users to set it to absurdly low levels like what is done with future client to equip totems faster in 32k and crystal fights to avoid getting killed while still having totems.

**Comment by S-B99** [comment]
What would the range be?

**Comment by ub3rshadow** [comment]
Probably between 0 delay and double what it is currently.

**Comment by S-B99** [comment]
There is no maximum currently

**Comment by ub3rshadow** [comment]
Is there not? kami's autototem from my experience takes a while to equip when you compare it to future's for example. Been able to see the difference from totems moving into my offhand and getting moved back to my inventory on endcrystal.me since it hates all forms of autototem. Future users' offhand is flickering with a totem incredibly more rapidly than kami users'.

**Comment by S-B99** [comment]
Oh I see what you mean. I thought there was a setting with the old setting sliders.

I'll add a slider with settings depending on what the current one is

**Comment by S-B99** [comment]
Also about flickering, there is a force setting but I'm not sure if it's public yet, but there's a new jar for testing

**Comment by blockparole** [comment]
> 
> 
> Probably between 0 delay and double what it is currently.

2 * 0 is still 0

**Comment by blockparole** [comment]
https://github.com/S-B99/KAMI/blob/bdbbd06ae7de6b8c450b733b378d28af3cc7a1fa/src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.java#L70
->
https://github.com/S-B99/KAMI/blob/bdbbd06ae7de6b8c450b733b378d28af3cc7a1fa/src/main/java/me/zeroeightsix/kami/module/ModuleManager.java#L60
https://github.com/S-B99/KAMI/blob/bdbbd06ae7de6b8c450b733b378d28af3cc7a1fa/src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTotem.java#L23

**Comment by blockparole** [comment]
Maybe doing this via windowClick -> ClickType.SWAP would be an enhancement.

**Comment by S-B99** [comment]
Yea I saw that the other day as well. 
I can't make the delay lower but I can add an option to wait to put it in

**Comment by blockparole** [comment]
Slot 1 is the upper left crafting slot.

Also the slot numbers depend on the opened inventory if any:
![](https://wiki.vg/images/1/13/Inventory-slots.png)
![](https://wiki.vg/images/e/e7/Dispenser-slots.png)
![](https://wiki.vg/images/1/19/Chest-slots.png)

But! Right now it just cancels action on open inv. For the Autototem to work while menus open, you would have to remove [this](https://github.com/S-B99/KAMI/blob/bdbbd06ae7de6b8c450b733b378d28af3cc7a1fa/src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTotem.java#L24) line. Ideally you wanna use the `EntityEquipmentSlot.OFFHAND` to adress the offhand slot.

**Comment by S-B99** [comment]
Meat meant to say slot 36, and I'm not sure why 086 had it cancel on opened inv. Also need a check for chests because then that slot is different?

**Comment by blockparole** [comment]
uh i forgot to post the wiki link, just check here: [link](https://wiki.vg/Inventory)

**Comment by blockparole** [comment]
The cancel on inv is in for a reason i guess. probably desync or smthg.

**Comment by S-B99** [comment]
Maybe? But Future does it while inv is opened iirc. I'll test how your inventory behaves with it removed I guess.

**Comment by S-B99** [comment]
@ub3rshadow i tested kami's autototem on endcrystal.me and there isn't a difference in speed that I can see, and there shouldn't be either. I'll look into adding an option for a hotbar totem

**Comment by S-B99** [comment]
I haven't had an issue with opened inventories, I added the option to the latest preview

**Comment by S-B99** [comment]
What I said earlier is dumb, no need to check, it works
